/* Imports */
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";

/* Font */
const font = Nunito({ subsets: ["latin"] });

/* Metadata */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* Layout */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body className={font.className}>
          <Toaster />
          {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
